[project]
name = "fizzy"
revision = "1.0"

[profiles.default]
MULTI_TENANT = { required = false }

BUNDLE_PATH = { required = true }
GEM_HOME = { required = true }
LD_LIBRARY_PATH = { required = true, provider = "env" }

[profiles.production]
SECRET_KEY_BASE = { description = "bin/rails secret", required = true }

MAILER_FROM_ADDRESS = { required = true }
SMTP_ADDRESS = { required = true }
SMTP_PASSWORD = { required = true }
SMTP_USERNAME = { required = true }

BASE_URL = { description = "The public URL of your Fizzy instance (e.g., `https://fizzy.example.com`). Used when generating links.", required = true }

VAPID_PRIVATE_KEY = { description = "For sending notifications", required = true }
VAPID_PUBLIC_KEY = { description = "For sending notifications", required = true }

RAILS_ENV = { default = "production", required = false }
BUNDLE_DEPLOYMENT = { default = "1", required = false}
BUNDLE_WITHOUT = { default = "development:test", required = false}
